version: "3.9"
services:
    devcontainer:
        container_name: devcontainer-${USER}
        image: devcontainer-${USER}
        platform: linux/arm64
        build:
            context: .
            target: base
        ports:
            - "8888:8888"
        volumes:
            - ./:/code
        command: bash -c "jupyter lab . --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/code --allow-root"
